recipe: default.v1
language: zh

pipeline:
- name: MitieNLP
  model: data/total_word_feature_extractor_zh.dat
- name: JiebaTokenizer
  dictionary_path: data/jieba_userdict
- name: MitieEntityExtractor
- name: EntitySynonymMapper
- name: RegexFeaturizer
- name: MitieFeaturizer
#- name: SklearnIntentClassifier
- name: DIETClassifier
  epochs: 100


policies:
- name: "TEDPolicy"
  epochs: 50
- name: "MemoizationPolicy"
  max_history: 5
- name: "RulePolicy"

# featurizer:
# - name: MaxHistoryTrackerFeaturizer
#   max_history: 5
#   state_featurizer:
#   - name: BinarySingleStateFeaturizer
# - name: "FallbackPolicy"
#   nlu_threshold: 0.4
#   core_threshold: 0.3
#   fallback_action_name: action_donknow
